# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e8931e7c5c40683c4b20f8f3ce926210b1c2bdcc83b4a569b7793b2df19c8e6f95e1d42637014f8571dada08b241c0d475fbe9cfa63cde0aa4bbd85d5d4894

test:
  secret_key_base: a4d3c5f22f3b208d57050f32f0018af40cbd7e3dd46e55c60af00928afc29d6eb71e66e5fd034c9ed8571eef73af435ad9606e2ecbb0137787cde2267185f07c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
